name: Build and upload your app to Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'My release notes'
        description: 'Release Notes Description'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug - Execute Gradle command - assembleDebug
        run: ./gradlew assembleDebug

      - name: Upload build to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.FIREBASE_CREDENTIALS}}
          testers: 'andy.edralin.iv@gmail.com'
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{inputs.release_notes}}